### ISSUE TITLE
Media library : Unknown column 't0._softDeletedAt' in 'where clause'

### ISSUE THREAD

**Issue by t-fritsch** [ChristopheCVB/strapi-plugin-soft-delete#6]
Hi,

When trying to edit a media from media library (Media library >  Click on media > "Replace media" button) I get the following error : 

> Exception has occurred:  Error: select `t0`.`id` from `files` as `t0` where (`t0`.`id` = 2 and `t0`.`_softDeletedAt` is null) limit 1 
> Unknown column 't0._softDeletedAt' in 'where clause'

I've tried to debug and I think that the source of the problem is here : 
https://github.com/ChristopheCVB/strapi-plugin-soft-delete/blob/e504c09aeb20e39caf5ff2da65255afb3dc91c09/server/bootstrap.ts#L102

Shouldn't the test include the same filtering as done in the entityService overrides ?
https://github.com/ChristopheCVB/strapi-plugin-soft-delete/blob/e504c09aeb20e39caf5ff2da65255afb3dc91c09/server/bootstrap.ts#L120

Note that I've had this bug with other scenarios working with media library that I haven't been able to reproduce.

- Node.js version: 20
- Strapi version: 4.15.0
- Database: mysql
- Operating system: macos
- Is your project Javascript or Typescript: TS

**Comment by t-fritsch** [comment]
Thanks a lot for the fix @ChristopheCVB ! 🙏 
Has it been published on npm alongside with 0.9.4 release ? (I wonder because the commit was made after the package.json bump)

**Comment by ChristopheCVB** [comment]
It has yes

**Comment by t-fritsch** [comment]
Great ! Thank you ! I will try it asap
