### ISSUE TITLE
Custom collection entity deletion from Content Manager throws Error and halts the dev server.

### ISSUE THREAD

**Issue by murphesi** [ChristopheCVB/strapi-plugin-soft-delete#7]
### Required System information

- Node.js version: 18.18.2
- NPM version: 10.2.4
- YARN: 1.22.21
- Strapi version: 4.15.0
- Database: sqlite
- Operating system: Ubuntu 22.04
- Is your project Javascript or Typescript: TS

### Describe the bug

When deleting a custom collection entity from the Content Manager an Error is thrown and halts the dev server.

Error 
```
node_modules/strapi-plugin-soft-delete/node_modules/@strapi/utils/dist/index.js
throw new Error("Missing schema in defaultSanitizeOutput");
Missing schema in defaultSanitizeOutput
```

### Steps to reproduce the behavior

1. Running locally `yarn dev`
2. Go to Content Manager
3. Delete entry for a custom collection

### Expected behavior

Shouldn't throw an Error and halt the server.

### Code snippets

It appears that `params.uid` is undefined [HERE](https://github.com/ChristopheCVB/strapi-plugin-soft-delete/blob/master/server/utils/index.ts#L32)

console output for `params`
```
{
  uid: undefined,
  event: 'entry.delete',
  action: 'soft-delete',
  entity: {
    id: 57,
    uuid: '...',
    note: '...',
    total: 73,
    currency: '...',
    createdAt: '2023-12-21T14:08:35.126Z',
    updatedAt: '2023-12-21T21:39:43.356Z',
    status: 'pending',
    _softDeletedAt: '2023-12-21T21:39:43.353Z',
    _softDeletedById: 2,
    _softDeletedByType: 'admin'
  }
}
```

Simply checking if `params.uid` is empty and returning `if (!params.uid) return;` bypasses the issue with no thoroughly verified side effects.

### Additional context

I can see the `Order` is properly deleted and I can access and Restore it from the `Soft Delete` menu.

I have also upgraded the plugin to strapi `4.15.0` and it appears to function as expected, but still contains the bug.

I have patched the plugin locally for now.

Looking forward to feedback.

**Comment by staniborII** [comment]
@murphesi I am facing the same problem. I noticed it happens only when i select and delete a single/multiple entries. how did you fix this locally?

**Comment by anthonytamez** [comment]
> @murphesi I am facing the same problem. I noticed it happens only when i select and delete a single/multiple entries. how did you fix this locally?

@staniborII you can use [patch-package](https://github.com/ds300/patch-package#readme). This local patch worked for me based on @murphesi recommendation using patch-package:

```
diff --git a/node_modules/strapi-plugin-soft-delete/dist/server/utils/index.js b/node_modules/strapi-plugin-soft-delete/dist/server/utils/index.js
index 5e664e9..f5f35fe 100644
--- a/node_modules/strapi-plugin-soft-delete/dist/server/utils/index.js
+++ b/node_modules/strapi-plugin-soft-delete/dist/server/utils/index.js
@@ -15,6 +15,7 @@ const getService = (name) => {
 };
 exports.getService = getService;
 const eventHubEmit = async (params) => {
+    if (!params.uid) return;
     const modelDef = strapi.getModel(params.uid);
     const sanitizedEntity = await utils_1.sanitize.sanitizers.defaultSanitizeOutput(modelDef, params.entity);
     strapi.eventHub.emit(params.event, {
diff --git a/node_modules/strapi-plugin-soft-delete/server/utils/index.ts b/node_modules/strapi-plugin-soft-delete/server/utils/index.ts
index 6c541d9..521c636 100644
--- a/node_modules/strapi-plugin-soft-delete/server/utils/index.ts
+++ b/node_modules/strapi-plugin-soft-delete/server/utils/index.ts
@@ -29,6 +29,7 @@ declare type CustomEventHubEmit = {
 });
 
 export const eventHubEmit = async (params: CustomEventHubEmit) => {
+  if (!params.uid) return;
   const modelDef = strapi.getModel(params.uid);
   const sanitizedEntity = await sanitize.sanitizers.defaultSanitizeOutput(
     modelDef,
```

**Comment by staniborII** [comment]
@anthonytamez Thanks. That worked neatly

**Comment by ChristopheCVB** [comment]
> > @murphesi I am facing the same problem. I noticed it happens only when i select and delete a single/multiple entries. how did you fix this locally?
> 
> @staniborII you can use [patch-package](https://github.com/ds300/patch-package#readme). This local patch worked for me based on @murphesi recommendation using patch-package:
> 
> ```
> diff --git a/node_modules/strapi-plugin-soft-delete/dist/server/utils/index.js b/node_modules/strapi-plugin-soft-delete/dist/server/utils/index.js
> index 5e664e9..f5f35fe 100644
> --- a/node_modules/strapi-plugin-soft-delete/dist/server/utils/index.js
> +++ b/node_modules/strapi-plugin-soft-delete/dist/server/utils/index.js
> @@ -15,6 +15,7 @@ const getService = (name) => {
>  };
>  exports.getService = getService;
>  const eventHubEmit = async (params) => {
> +    if (!params.uid) return;
>      const modelDef = strapi.getModel(params.uid);
>      const sanitizedEntity = await utils_1.sanitize.sanitizers.defaultSanitizeOutput(modelDef, params.entity);
>      strapi.eventHub.emit(params.event, {
> diff --git a/node_modules/strapi-plugin-soft-delete/server/utils/index.ts b/node_modules/strapi-plugin-soft-delete/server/utils/index.ts
> index 6c541d9..521c636 100644
> --- a/node_modules/strapi-plugin-soft-delete/server/utils/index.ts
> +++ b/node_modules/strapi-plugin-soft-delete/server/utils/index.ts
> @@ -29,6 +29,7 @@ declare type CustomEventHubEmit = {
>  });
>  
>  export const eventHubEmit = async (params: CustomEventHubEmit) => {
> +  if (!params.uid) return;
>    const modelDef = strapi.getModel(params.uid);
>    const sanitizedEntity = await sanitize.sanitizers.defaultSanitizeOutput(
>      modelDef,
> ```

Hi there!

Maybe you could open a PR to fix this?

Thanks ;)
