### ISSUE TITLE
Server will be crashed in batch delete

### ISSUE THREAD

**Issue by godanytamas** [ChristopheCVB/strapi-plugin-soft-delete#9]
### Required System information

- Node.js version: v18.12.0
- NPM version:
- Strapi version: 4.14.4
- Database:
- Operating system: OSX
- Is your project Javascript or Typescript: Javascript

### Describe the bug

If you select one or more records from the list with the checkbox at the beginning of the rows and after that push the delete button, then the server has been crashed with the following exception:

`node_modules/strapi-plugin-soft-delete/node_modules/@strapi/utils/dist/index.js:1957
    throw new Error("Missing schema in defaultSanitizeOutput");`

### Steps to reproduce the behavior

1. Go to a collection list on admin dashboard
2. Select one or more records from the list
3. The delete button will be shown after the first record has been selected. Push the delete button
4. The server will be crashed.

**Comment by mukesh-thakur-dy** [comment]
@godanytamas Did you find any solution?
